cart/urls.py
from django.urls import path
from .views import  cart_detail,  cart_add, cart_remove, cart_product_update, cart_one_add

app_name = 'cart'

urlpatterns = [
   path('', cart_detail, name='cart_detail'),
   path('cart_one_add/<int:product_id>/', cart_one_add, name='cart_one_add'),
   # path('checkout', CheckoutView.as_view(), name='CheckoutView'),
   path('add/<int:product_id>/', cart_add, name='cart_add'),
   # path('ajouter-au-panier', cart_add_one_product, name='cart_add_one_product'),
   path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
   path('update/', cart_product_update, name='cart_product_update'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', include("core.urls")),
    path('', include("business.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include("order.urls")),
    path('coupons/', include("coupons.urls")),
    path('delivery/', include("delivery.urls")),
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += path('admin/', admin.site.urls),
else:
    urlpatterns += path('kahraba-admin/', admin.site.urls),

core/urls.py
from django.urls import path, re_path
from .views import IndexView, AboutView, ContactView,  ProductsView, ProductsView, ProductDetailView, VirementBancaireView, CarteBancaireView ,PaiementView ,PaiementEspecesView ,EchangeView ,LivraisonView ,RetourView,  product_detail, filtred_htmx_products, sorted_htmx_products

app_name = 'core'

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('produits/', ProductsView.as_view(), name='products'),
    # path('filtres-produits/', filtered_view, name='filtered-products'),
    path('produits-filtered/', filtred_htmx_products, name='filtered-products'),
    path('produits-sorted/', sorted_htmx_products, name='sorted-products'),
    path('product-detail/', product_detail, name='product-detail'),

    # path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-cat'),
    # path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-sub-cat'),
    path('produits/produit/<slug:slug>/', ProductDetailView.as_view(), name='productDetail'),


    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    #  PAIEMENT URLS

    path('virement-bancaire/', VirementBancaireView.as_view(), name='virement-bancaire'),
    path('carte-bancaire/', CarteBancaireView.as_view(), name='crte-bancaire'),
    path('paiement/', PaiementView.as_view(), name='paiement'),
    path('paiement-especes/', PaiementEspecesView.as_view(), name='paiement-especes'),
    #  Livraison URLS
    path('echange/', EchangeView.as_view(), name='echange'),
    path('livraison/', LivraisonView.as_view(), name='livraison'),
    path('retour/', RetourView.as_view(), name='retour'),

]

core/forms.py
from django import forms
from .models import ContactForm

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = ['name','phone','email','subject','message']

core/views.py
from django.db.models import Q
from django.http.response import HttpResponse 
from atributes.models import Tag
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse, request
from .forms import ContactForm
from delivery.models import Wilaya, Commune
from django.views.generic import TemplateView, DetailView, ListView, CreateView, View
from .models import Brand, Gamme, Product, Category
from business.models import Business, ThreePhotos, Slide, DualBanner, Counter, LargeBanner
from cart.forms import CartAddProductForm
from business.models import Counter
from .filters import ProductFilter
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.forms import CartAddProductForm
from django.db.models import F
from django.core.management.utils import get_random_secret_key


class IndexView(TemplateView):
    template_name = "index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["new_products"] = Product.objects.filter(new=True, actif=True)[:10]
        context["top_products"] = Product.objects.filter(top=True, actif=True)[:10]
        context["big_slides"]   = Slide.objects.filter(actif=True)
        context["three_photos"] = ThreePhotos.objects.all()[:3]
        context["dual_banners"] = DualBanner.objects.all()[:2]
        context["large_banner"] = LargeBanner.objects.last()
        context["random_cat"]   = Category.objects.filter(actif=True)
        print(get_random_secret_key())
        all_cat = Category.objects.filter(actif=True)
        cat_list = []
        for cat in all_cat:
            if cat.products.all().count() > 0:
                cat_list.append(cat)
        print('categories ', cat_list)
        context["random_cat"] = cat_list[:3]
        print('a tchou hadi', context["random_cat"])
        return context


class AboutView(TemplateView):
    template_name = "about.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["counters"] = Counter.objects.filter(actif=True)[:4]
        return context

class VirementBancaireView(TemplateView):
    template_name = "paiement/virement-bancaire.html"

class CarteBancaireView(TemplateView):
    template_name = "paiement/carte-bancaire.html"

class PaiementView(TemplateView):
    template_name = "paiement/paiement.html"

class PaiementEspecesView(TemplateView):
    template_name = "paiement/paiement-especes.html"



class EchangeView(TemplateView):
    template_name = "livraison/echange.html"

class LivraisonView(TemplateView):
    template_name = "livraison/livraison.html"

class RetourView(TemplateView):
    template_name = "livraison/retours.html"


def product_detail(request):
    product = Product.objects.get(id=Product.objects.first().id)
    return render(request, 'snippets/product-modal.html', {'product': product})


class ProductsView(ListView):
    context_object_name = 'products'
    model = Product
    template_name = "products.html"
    paginate_by = 24
    def get_queryset(self):
        try:
            param = self.request.GET.get('category')
            # print('category', param)
            if param == 'all':
                category = Category.objects.filter(actif=True)
                products = Product.objects.filter(actif=True)
            elif param is None:
                category = Category.objects.filter(actif=True)
                products = Product.objects.filter(actif=True)
            else:
                category = Category.objects.get(id = param)
                products = Product.objects.filter(category__in=category.get_descendants(include_self=True))
        except:
            try:
                new = self.request.GET.get('new')
                if new == 'new':
                    products = Product.objects.filter(new=True)
                elif new == 'promo':
                    products = Product.objects.filter(old_price=True)
                else:
                    pass
            except:
                category = Category.objects.filter(actif=True)
                products = Product.objects.filter(actif=True)
        query = self.request.GET.get('name')
        if query:
            # print('query', query)
            qs = products.search(query=query)
            # print('les produits ')
        else:
            # print('les ELSEEEE ', products)
            qs = products
        return qs
        # except:
        #     print(' kamel les produits kharjou :) excepty !!!')
        #     return super().get_queryset() 
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.GET.get('category'):
            try:
                category = self.request.GET.get('category')
                if category == 'all':                
                    context["category"] = Category.objects.filter(actif=True)
                else:                
                    context["category"] = Category.objects.get(id = category)
            except:
                pass
        # context["tags"] = Tag.objects.all()
        context["brands"] = Brand.objects.filter(actif=True)
        gammes = Gamme.objects.filter(actif=True).exclude(name=F('brand__name'))
        context["gammes"] = gammes
        context["filters"] = ProductFilter(self.request.GET, queryset= self.get_queryset())
        # context["products"] = Product.objects.all()
        return context


def filtred_htmx_products(request):
    context = {}
    # print('request', request.GET)
    products = ProductFilter(request.GET, queryset= Product.objects.all())
    context['products'] = products.qs[:24]
    print('context[products]', context['products'])
    return render(request, 'snippets/htmx_products.html', context)

# def sorted_htmx_products(request):
#     context = {}
#     params= request.GET.get('order_by','')
#     print('request.GET', request.GET)
#     print('request params', request.GET.get('order_by'))
#     print('requestccccc', params)
#     if params == "name_a":
#         querySet = Product.objects.all().order_by('name')
#     elif params == "name_z":
#         querySet = Product.objects.all().order_by('-name')
#     elif params == "price":
#         querySet = Product.objects.all().order_by('price')
#     elif params == "brand":
#         querySet = Product.objects.all().order_by('gamme_brand')
#     else:
#         print('je sui laaa')
#         querySet = Product.objects.all()
#     products = ProductFilter(request.GET, queryset=querySet )
#     print('sorted products', products.qs)
#     context['products'] = products.qs
#     return render(request, 'snippets/htmx_products.html', context)
    # return HttpResponse('hello')

def sorted_htmx_products(request):
    context = {}
    print('request.GET', request.GET)
    print('request params', request.GET.get('order_by'))

    querySet = Product.objects.all()
    products = ProductFilter(request.GET, queryset=querySet )
    print('sorted products', products.qs)
    context['products'] = products.qs
    # return render(request, 'snippets/htmx_products.html', 0context)
    return HttpResponse('hello')



class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = "product-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["related"] = Product.objects.filter(actif=True).order_by('?')[:4] 
        context["wilayas"] = Wilaya.objects.all().order_by('name') 
        prod = self.get_object()
        category = prod.category
        products =  Product.objects.filter(category = category)
        context["related_products"] = products.exclude(id= prod.id).order_by('?')[:8]
        context["related_products_count"] = products.count() - 1
        context['form'] = CartAddProductForm()
        # context['atributes'] = prod.product_type.atributes.all()
        return context
    

class ContactView(CreateView):
    template_name = 'contact.html'
    form_class = ContactForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
  
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
      
        message = 'Une erreur est survenue, veuillez réessayer.'
        success = False
        try:
            #save the form   
            if form.is_valid():
                form.save()
                #messages.success(request, 'Votre message a bien été envoyé')
                message = 'Votre message a bien été envoyé!'
                success = True
                print(success)
                return render(request, 'other/contact.html', {'message': message, 'success': success})
            else:
                print(success)
                message = 'Une erreur est survenue, veuillez réessayer.'
                return render(request, 'contact.html', {'message': message, 'failure': True})
        except:
            return render(request, 'contact.html', {'message': message, 'failure': True})
        return render(request, 'contact.html', {'message': message, 'failure': True})


# def set_if_not_none(mapping, key, value):
#     if value is not None:
#         mapping[key] = value

core/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'core:index' %}">Accueil</a></li>
                            <li class="active">Contact</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->     
            <!-- Begin Contact Main Page Area -->
            <div class="contact-main-page mt-60 mb-40 mb-md-40 mb-sm-40 mb-xs-40">
                <div class="container mb-60">
                    {% if business.google_maps %}
                    <div id="google-map">
                        {{business.google_maps|safe}}
                    </div>
                    {% endif %}
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-5 offset-lg-1 col-md-12 order-1 order-lg-2">
                            <div class="contact-page-side-content">
                                <h3 class="contact-page-title">Contactez nous</h3>
                                <p class="contact-page-message mb-25">{{business.contact_message}}</p>
                                <div class="single-contact-block">
                                    <h4><i class="fa fa-fax"></i> Addresse</h4>
                                    <p>{{business.adress}}</p>
                                </div>
                                <div class="single-contact-block">
                                    <h4><i class="fa fa-phone"></i> Téléphone</h4>
                                    <p>{{business.phone}}</p>
                                    <p>{{business.phone2}}</p>
                                </div>
                                <div class="single-contact-block last-child">
                                    <h4><i class="fa fa-envelope-o"></i> Emails</h4>
                                    {% if business.email %}
                                        <p>{{business.email}}</p>
                                    {% endif %} 
                                    {% if business.email2 %}
                                        <p>{{business.email2}}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12 order-2 order-lg-1">
                            <div class="contact-form-content pt-sm-55 pt-xs-55">
                                <h3 class="contact-page-title">Laisser Un Message</h3>
                                <div class="contact-form">
                                    <form action="{% url 'core:contact' %}" method=POST >
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label>Votre Nom<span class="required">*</span></label>
                                            <input type="text" name="name" id="customername" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Votre Email <span class="required">*</span></label>
                                            <input type="email" name="email" id="customerEmail" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Téléphone<span class="required">*</span></label>
                                            <input type="phone" name="phone" id="customerPhone" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Sujet</label>
                                            <input type="text" name="subject" id="contactSubject">
                                        </div>
                                        <div class="form-group mb-30">
                                            <label>Votre Message</label>
                                            <textarea name="message" id="message" ></textarea>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" value="submit" id="submit" class="li-btn-3" name="submit">Envoyer</button>
                                        </div>
                                    </form>
                                </div>
                                <p class="form-messege"></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Contact Main Page Area End Here -->
         

<!-- contact32:04-->
{% endblock %}

core/templates/product-detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        {% with product.category as category %}
                        <ul>
                            <li><a href="{% url 'core:index' %}">Acceuil</a></li>
                            {% for cat in category.get_ancestors %}
                                <li><a href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                            {% endfor %}
                            <li ><a href="{{product.category.get_absolute_url}}"> {{product.category}} </a></li>
                            <li class="active"> {{product.name}}</li>
                        </ul>
                        {% endwith %}
                    </div>
                </div>
            </div>
            <div class="content-wraper">
                <div class="container">
                    <div class="row single-product-area">
                        <div class="col-lg-5 col-md-6">
                            <div class="product-details-left sp-tab-style-left-page">
                                <div class="product-details-images slider-navigation-1">
                                    {% for photo in product.photos.all %}
                                        <div class="lg-image">
                                            <a class="popup-img venobox vbox-item" href="{{photo.fichier.url}}" data-gall="myGallery">
                                                <img src="{{photo.fichier.url}}" alt="product image">
                                            </a>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="tab-style-left">
                                    {% for photo in product.photos.all %}
                                        <div class="sm-image"><img src="{{photo.fichier.url}}" alt="product image thumb"></div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7 col-md-6">
                            <form action="{% url 'cart:cart_add' product.pk %}" method="POST" class="cart-quantity">
                                <div class="product-details-view-content pt-60">
                                    <div class="product-info">
                                        <h2>{{product.name}}</h2>
                                        {% if product.brand %}
                                            <span class="product-details-ref d-block">Marque: {{product.brand}}</span>
                                        {% endif %}
                                        {% if product.reference %}
                                            <span class="product-details-ref">Reference: {{product.reference}}</span>
                                        {% endif %}
                                        <div class="price-box pt-20">
                                            <span class="new-price new-price-2">Prix: </span>
                                            {% if product.old_price %}
                                                <span style="text-decoration: line-through;" class="old-price">{{product.old_price}} DA</span>
                                            {% endif %}
                                            <span class="new-price new-price-2"> {{product.price}} DA</span>
                                        </div>
                                        {% if product.text %}
                                            <div class="product-desc">
                                                <p>
                                                    <span>{{product.text}}</span>
                                                </p>
                                            </div>
                                        {% endif %}
                                        {% if product.product_type.atributes %}
                                            <div class="row d-flex" style="height: 200px">
                                                {% for atribute in atributes %}
                                                    <div class="product-variants col-3">
                                                        <div class="produt-variants-size">
                                                            <label>{{atribute.name}}</label>
                                                            <select class="nice-select"  name="{% if forloop.counter == 1 %}attribute_1{% elif forloop.counter == 2 %}attribute_2{% elif forloop.counter == 3 %}attribute_3{% else %}atribute_4{% endif %}">
                                                        {% for value in atribute.values.all %}
                                                            <option value="{{value.value}}"{% if forloop.counter == 1 %} selected="selected" {% endif %}>{{value.value}}</option>
                                                        {% endfor %}
                                                            </select>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        {% endif %}
                                        <div class="single-add-to-cart">
                                            {% csrf_token %}
                                            <div class="quantity">
                                                <label>Quantité</label>
                                                <div class="cart-plus-minus">
                                                    <input class="cart-plus-minus-box" name="quantity" value="1" type="text">
                                                    <div class="dec qtybutton"><i class="fa fa-angle-down"></i></div>
                                                    <div class="inc qtybutton"><i class="fa fa-angle-up"></i></div>
                                                </div>
                                            </div>
                                            <button class="add-to-cart" type="submit">Ajouter au panier</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div> 
                    </div>
                </div>
            </div>
            <!-- content-wraper end -->
            <!-- Begin Product Area -->
            <div class="product-area pt-35">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="li-product-tab">
                                <ul class="nav li-product-menu">
                                    {% if product.description %}
                                        <li><a class="active" data-toggle="tab" href="#description"><span>Déscription</span></a></li>
                                    {% endif %}
                                    {% if product.specifications.count > 0 %}
                                        <li><a data-toggle="tab" href="#product-details"><span>Caractéristiques</span></a></li>
                                    {% endif %}
                                    {% if product.documents.count > 0 %}
                                        <li><a data-toggle="tab" href="#reviews"><span>Documents</span></a></li>
                                    {% endif %}
                                </ul>
                            </div>
                            <!-- Begin Li's Tab Menu Content Area -->
                        </div>
                    </div>
                    <div class="tab-content">
                        {% if product.description %}
                            <div id="description" class="tab-pane active show" role="tabpanel">
                                <div class="product-description">
                                   {{product.description|safe}}
                                </div>
                            </div>
                        {% endif %}
                        <div id="product-details" class="tab-pane" role="tabpanel">
                            <div class="product-details-manufacturer">
                                <table class="table table-striped">
                                    <tbody>
                                        {% for carec in product.specifications.all %}
                                            <tr>
                                                <th scope="row">{{carec.key}}</th>
                                                <td>{{carec.value}}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                  </table>
                            </div>
                        </div>
                        <div id="reviews" class="tab-pane" role="tabpanel">
                            <div class="product-reviews">
                                {% for doc in product.documents.all %}
                                    <li><i class="fa fa-file-pdf-o"></i> <a href="{{doc.file.url}}" download> {{doc.name}}</a></li>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <section class="product-area li-laptop-product pt-30 pb-50">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="li-section-title">
                                <h2>
                                    <span>{{related_products_count}} autres produits dans {{product.category}}</span>
                                </h2>
                            </div>
                            <div class="row">
                                <div class="product-active owl-carousel">
                                  {% for product in related_products %}
                                    <div class="col-lg-12">
                                        {% include "snippets/product-block.html" %}
                                    </div>
                                  {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
{% endblock content %}